env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./server/tsconfig.json
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  no-console: off
